const mongoose = require('mongoose');
const orderSchema = new mongoose.Schema({
shippingInfo:{
    hNo:{
         type:String,
         required:true,
    },
    city:{
        type:String,
        required:true,
    },
    state:{
        type:String,
        required:true,
    },
    country:{
        type:String,
        required:true,
    },
    pinCode:{
        type:Number,
        required:true,
    },
    phoneNo:{
        type:Number,
        required:true,
    },


},
orderItems:{
    cheeseBurger:{
        price:{
            type:Number,
            required:true,
        },
        quantity:{
            type:Number,
            required:true,
        },
    },
    vegCheeseBurger:{
        price:{
            type:Number,
            required:true,
        },
        quantity:{
            type:Number,
            required:true,
        },
    },
    burgerWithFries:{
        price:{
            type:Number,
            required:true,
        },
        quantity:{
            type:Number,
            required:true,
        },
    },
},
user:{
    type:mongoose.Schema.ObjectId,
    ref:'User',
    required:true,
},
paymentMethod:{
    type:String,
    enum :['COD',"Online"],
    default:'COD',
},
paymentInfo:{
    type:mongoose.Schema.ObjectId,
    ref:'Payment'
},
paidAt:{
    type:Date
},
itemsPrice:{
    type:Number,
    required:true,
},

taxPrice:{
    type:Number,
    required:true,
},
shippingCharges:{
    type:Number,
    required:true,
},
totalPrice:{
    type:Number,
    required:true,
},
orderStatus:{
    type:String,
    enum:['Preparing','Shipped','Delivered'],
    default:'Preparing',
},
deliveredAt:{
    type:Date
},
createdAt:{
    type:Date,
    default:Date.now,
},
});
const Order = mongoose.model('Order',orderSchema);
module.exports = Order;